name: Release-plz

permissions:
  pull-requests: write
  contents: write
  id-token: write # Required for trusted publishing

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Polymarket' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: '1.88'

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@e592230ad39e3ec735402572601fc621aa24355c # v0.5.124
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
